Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  
  # 共有ディレクトリの設定
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", mount_options: ['dmode=777', 'fmode=777']

  # ポートフォワードの設定
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 3306, host: 13306
  config.vm.network "forwarded_port", guest: 5432, host: 15432

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 3
    vb.memory = "8192"
  end

   config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    # Docker
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common make
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io
    sudo usermod -aG docker vagrant

    # Docker Compose
    mkdir -p /home/vagrant/.docker/cli-plugins
    curl -Lf -o /home/vagrant/.docker/cli-plugins/docker-compose "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-linux-x86_64"
    chmod +x /home/vagrant/.docker/cli-plugins/docker-compose
  SHELL
end
