Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  
  # 共有ディレクトリの設定
  config.vm.synced_folder "./shared", "/home/vagrant/shared"

  # ポートフォワードの設定
  config.vm.network "forwarded_port", guest: 80, host: 10080
  config.vm.network "forwarded_port", guest: 443, host: 10443
  config.vm.network "forwarded_port", guest: 3306, host: 13306
  config.vm.network "forwarded_port", guest: 5432, host: 15432

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = 3
    vb.memory = "8192"
    vb.customize [
      "modifyvm", :id,
      "--vram", "256", # グラフィックメモリ割当(フルスクリーンモード対応)
      "--clipboard", "bidirectional", # クリップボード共有
      "--draganddrop", "bidirectional", # ドラッグアンドドロップ
      "--accelerate3d", "on",
      "--hwvirtex", "on",
      "--nestedpaging", "on",
      "--largepages", "on",
      "--ioapic", "on",
      "--pae", "on",
      "--paravirtprovider", "kvm",
    ]
  end

   config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get upgrade -y
    apt-get install -y ubuntu-desktop
  SHELL
end
